### ISSUE TITLE
ESM error in v4

### ISSUE THREAD

**Issue by charlesfries** [ember-template-lint/ember-template-lint-plugin-prettier#197]
I'm seeing the following error after updating `ember-template-lint` and `ember-template-lint-plugin-prettier` to 4.0.0.

```
(node:1584) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js
require() of ES modules is not supported.
require() of C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\ember-template-lint-plugin-prettier.js from C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint\lib\get-config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename ember-template-lint-plugin-prettier.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\cfries\Documents\Repositories\etlpp\node_modules\ember-template-lint-plugin-prettier\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requirePlugin (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:38:12)
    at async processPlugins (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:150:16)
    at async getProjectConfig (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/get-config.js:396:22)
    at async Linter.loadConfig (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/linter.js:48:19)
    at async Linter.verify (file:///C:/Users/cfries/Documents/Repositories/etlpp/node_modules/ember-template-lint/lib/linter.js:304:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Reproduction: https://github.com/charlesfries/etlpp

```
"ember-cli": "~4.0.1",
"ember-source": "~4.0.1",
"ember-template-lint": "^4.0.0",
"ember-template-lint-plugin-prettier": "^4.0.0",
```

**Comment by dcyriller** [comment]
@charlesfries I took a look to the reproduction repo. GitHub Actions do indeed fail for the lint ([link](https://github.com/charlesfries/etlpp/runs/4780254027?check_suite_focus=true)). But there fail on a lint error, meaning the linting happens correctly.

Could it be possible that the error needs to be reproduced on the Windows platform?

**Comment by charlesfries** [comment]
> Could it be possible that the error needs to be reproduced on the Windows platform?

@dcyriller 🤦‍♂️ Good call. After further investigation, the true error seems to occur [here](https://github.com/ember-template-lint/ember-template-lint/blob/523d93cddb1953fb36111da33603270598da2e52/lib/get-config.js#L38):

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:777:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at Loader.import (internal/modules/esm/loader.js:176:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at requirePlugin (file:///C:/Users/cfries/Documents/Repositories/brokers/node_modules/ember-template-lint/lib/get-config.js:34:33)
    at processPlugins (file:///C:/Users/cfries/Documents/Repositories/brokers/node_modules/ember-template-lint/lib/get-config.js:151:22)
    at getProjectConfig (file:///C:/Users/cfries/Documents/Repositories/brokers/node_modules/ember-template-lint/lib/get-config.js:397:28)
    at async Linter.loadConfig (file:///C:/Users/cfries/Documents/Repositories/brokers/node_modules/ember-template-lint/lib/linter.js:48:19) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

**Comment by dcyriller** [comment]
I am giving this a second thought. Could you tell me what your node version is?

**Comment by charlesfries** [comment]
```
node -v v14.17.1
npm -v 8.1.2
```
